## H2 Test Database creds
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql = true




## SQL Scripts

sql.script.create.book=insert into book(author,category,rating,title) \
  values ('kareem', 'computer science', '3','coding')


sql.script.delete.book=DELETE FROM books; ALTER TABLE books ALTER COLUMN ID RESTART WITH 1
